column_mapping:
  id: "OBJECTID"
  event_unique_id: "EVENT_UNIQUE_ID"
  report_date: "REPORT_DATE"
  occ_date: "OCC_DATE"
  report_year: "REPORT_YEAR"
  report_month: "REPORT_MONTH"
  report_day: "REPORT_DAY"
  report_doy: "REPORT_DOY"
  report_dow: "REPORT_DOW"
  report_hour: "REPORT_HOUR"
  occ_year: "OCC_YEAR"
  occ_month: "OCC_MONTH"
  occ_day: "OCC_DAY"
  occ_doy: "OCC_DOY"
  occ_dow: "OCC_DOW"
  occ_hour: "OCC_HOUR"
  division: "DIVISION"
  location_type: "LOCATION_TYPE"
  premises_type: "PREMISES_TYPE"
  ucr_code: "UCR_CODE"
  ucr_ext: "UCR_EXT"
  offence: "OFFENCE"
  csi_category: "CSI_CATEGORY"
  hood_158: "HOOD_158"
  neighbourhood_158: "NEIGHBOURHOOD_158"
  hood_140: "HOOD_140"
  neighbourhood_140: "NEIGHBOURHOOD_140"
  long_wgs84: "LONG_WGS84"
  lat_wgs84: "LAT_WGS84"
  x: "x"
  y: "y"
