delimiter: ","
quote: "\""

column_mapping:
  row_id: "Row ID"
  incident_datetime: "Incident Datetime"
  incident_date: "Incident Date"
  incident_time: "Incident Time"
  incident_year: "Incident Year"
  incident_day_of_week: "Incident Day of Week"
  report_datetime: "Report Datetime"
  incident_id: "Incident ID"
  incident_number: "Incident Number"
  cad_number: "CAD Number"
  report_type_code: "Report Type Code"
  report_type_description: "Report Type Description"
  filed_online: "Filed Online"
  incident_code: "Incident Code"
  incident_category: "Incident Category"
  incident_subcategory: "Incident Subcategory"
  incident_description: "Incident Description"
  resolution: "Resolution"
  intersection: "Intersection"
  cnn: "CNN"
  police_district: "Police District"
  analysis_neighborhood: "Analysis Neighborhood"
  supervisor_district: "Supervisor District"
  supervisor_district_2012: "Supervisor District 2012"
  latitude: "Latitude"
  longitude: "Longitude"
  point: "Point"
  data_as_of: "data_as_of"
  data_loaded_at: "data_loaded_at"
