# Master template file that includes all templates
# This file imports all individual template files

import:
  - "postgres_customer_orders.yaml"
  - "business_intelligence_templates.yaml"
  - "advanced_analytics_templates.yaml"
  - "comparative_analysis_templates.yaml"

# Note: This approach requires modifying the template loader to support imports
# Otherwise, you'll need to manually merge all templates into this file