# Adapter configurations for ORBIT
# This file contains all adapter definitions and can be imported by config.yaml

adapters:
  - name: "qa-sql"
    type: "retriever"
    datasource: "sqlite"
    adapter: "qa"
    implementation: "retrievers.implementations.qa.QASSQLRetriever"
    config:
      # QA-specific settings
      confidence_threshold: 0.3
      max_results: 5
      return_results: 3
      
      # Unified retriever features (available for all SQL adapters)
      use_connection_pool: false  # SQLite doesn't support traditional pooling (file-based)
      pool_size: 1  # Not applicable for SQLite
      connection_timeout: 30  # Connection timeout in seconds
      
      # Query monitoring (automatically provided by unified base)
      enable_query_monitoring: true
      query_timeout: 5000  # 5 seconds
      
      # Security and access control (recommended)
      table: "city"  # Specify the exact table for single-table access
      allowed_columns: ["id", "question", "answer", "category", "confidence"]  # Limit accessible columns
      security_filter: "active = 1"  # Only return active Q&A pairs
      
      # Performance optimization
      cache_ttl: 1800  # Cache results for 30 minutes
      
    # Fault tolerance settings for this adapter
    fault_tolerance:
      operation_timeout: 15.0          # Lower timeout for local database operations
      failure_threshold: 10            # Higher threshold for local operations (more reliable)
      recovery_timeout: 30.0           # Short base timeout for local DB
      success_threshold: 5             # Multiple successes to close circuit
      max_recovery_timeout: 120.0      # Max 2 minutes for local DB
      enable_exponential_backoff: true # Enable backoff for local DB
      enable_thread_isolation: false   # No isolation needed for local SQLite operations
      enable_process_isolation: false  # SQLite is lightweight, no process isolation needed
      max_retries: 3                   # Retry failed queries
      retry_delay: 0.5                 # Short delay between retries for local DB
      cleanup_interval: 3600.0         # Clean up stats every hour
      retention_period: 86400.0        # Keep stats for 24 hours
      event_handler:
        type: "default"                # Use default filesystem logger
      
  - name: "qa-vector-chroma"
    type: "retriever"
    datasource: "chroma"
    adapter: "qa"
    implementation: "retrievers.implementations.qa.QAChromaRetriever"
    config:
      collection: "city"
      confidence_threshold: 0.3
      distance_scaling_factor: 200.0
      embedding_provider: null
      max_results: 5
      return_results: 3
      
    fault_tolerance:
      operation_timeout: 25.0
      failure_threshold: 3
      recovery_timeout: 60.0
      success_threshold: 2
      max_recovery_timeout: 600.0
      enable_exponential_backoff: true
      enable_thread_isolation: true
      enable_process_isolation: false
      max_retries: 2
      retry_delay: 1.0
      cleanup_interval: 1800.0
      retention_period: 43200.0
      event_handler:
        type: "default"
      
  # - name: "qa-vector-qdrant"
  #   type: "retriever"
  #   datasource: "qdrant"
  #   adapter: "qa"
  #   implementation: "retrievers.implementations.qa.QAQdrantRetriever"
  #   config:
  #     collection: "city"
  #     confidence_threshold: 0.3
  #     score_scaling_factor: 200.0
  #     embedding_provider: null
  #     max_results: 5
  #     return_results: 3
      
  #   fault_tolerance:
  #     operation_timeout: 10.0
  #     failure_threshold: 2
  #     recovery_timeout: 45.0
  #     success_threshold: 1
  #     max_recovery_timeout: 300.0
  #     enable_exponential_backoff: true
  #     enable_thread_isolation: true
  #     enable_process_isolation: false
  #     max_retries: 1
  #     retry_delay: 1.0
  #     cleanup_interval: 1800.0
  #     retention_period: 43200.0
  #     event_handler:
  #       type: "default"
      
  - name: "file-vector"
    type: "retriever"
    datasource: "chroma"
    adapter: "file"
    implementation: "retrievers.implementations.file.FileChromaRetriever"
    config:
      confidence_threshold: 0.1
      distance_scaling_factor: 150.0
      embedding_provider: null
      max_results: 10
      return_results: 5
      # File-specific settings
      include_file_metadata: true
      boost_file_uploads: true
      file_content_weight: 1.5
      metadata_weight: 0.8
      
    fault_tolerance:
      operation_timeout: 35.0
      failure_threshold: 5
      recovery_timeout: 45.0
      success_threshold: 3
      max_recovery_timeout: 300.0
      enable_exponential_backoff: true
      enable_thread_isolation: true
      enable_process_isolation: false
      max_retries: 3
      retry_delay: 2.0
      cleanup_interval: 7200.0
      retention_period: 172800.0
      event_handler:
        type: "default"
        
  # New refactored implementation with unified base classes
  - name: "intent-sql-postgres"
    type: "retriever"
    datasource: "postgres"
    adapter: "intent"
    implementation: "retrievers.implementations.intent.IntentPostgreSQLRetriever"
    config:
      # Path to the domain definition file
      domain_config_path: "config/sql_intent_templates/customer_order_domain.yaml"
      # Path to the SQL template library
      # Option 1: Single file (original approach)
      # template_library_path: "config/sql_intent_templates/postgres_customer_orders.yaml"
      
      # Option 2: Multiple template files (requires adapter modification)
      template_library_path: 
        - "config/sql_intent_templates/postgres_customer_orders.yaml"
        - "config/sql_intent_templates/business_intelligence_templates.yaml"
        - "config/sql_intent_templates/advanced_analytics_templates.yaml"
        - "config/sql_intent_templates/comparative_analysis_templates.yaml"
      # Name for the vector store collection for templates
      template_collection_name: "intent_query_templates"
      confidence_threshold: 0.75
      # Embedding provider for template matching (null = use default)
      embedding_provider: null
      # Maximum templates to consider
      max_templates: 5
      # Return top N results
      return_results: 10
      # ChromaDB persistence settings
      chroma_persist: true  # Set to true to persist embeddings between runs
      chroma_persist_path: "./chroma_db/intent_templates"  # Path for persistent storage
      reload_templates_on_start: true  # Whether to reload templates on startup (when using persistent storage)
      force_reload_templates: true  # Force reload even if templates exist in persistent storage
      
      # Unified retriever features
      use_connection_pool: true  # Enable connection pooling
      pool_size: 5  # Connection pool size
      connection_timeout: 30  # Connection timeout in seconds
      
      # Query monitoring (automatically provided by new base)
      enable_query_monitoring: true
      query_timeout: 5000  # 5 seconds
      
    # Fault tolerance settings (same as original)
    fault_tolerance:
      operation_timeout: 20.0
      failure_threshold: 5
      recovery_timeout: 45.0
      success_threshold: 3
      max_recovery_timeout: 300.0
      enable_exponential_backoff: true
      enable_thread_isolation: true
      enable_process_isolation: false
      max_retries: 3
      retry_delay: 1.0
      cleanup_interval: 3600.0
      retention_period: 86400.0
      event_handler:
        type: "default"
