column_mapping:
  id: "OBJECTID"
  incident_id: "ID"
  year: "Year"
  reported_date: "Reported Date"
  occurred_date: "Occurred Date"
  weekday: "Day of Week"
  offence_category: "Offence Category"
  bicycle_style: "Bicycle Style"
  bicycle_value: "Bicycle Value"
  bicycle_make: "Bicycle Make"
  bicycle_model: "Bicycle Model"
  bicycle_type: "Bicycle Type"
  bicycle_frame: "Bicycle Frame"
  bicycle_colour: "Bicycle Colour"
  bicycle_speed: "Bicycle Speed"
  neighbourhood: "Neighbourhood"
  sector: "Sector"
  division: "Division"
  census_tract: "Census Tract"
  status: "Status"
  intersection: "Intersection"
  time_of_day: "Time of Day"
  ward: "Ward"
  councillor: "Councillor"
  reported_hour: "Reported Hour"
  occurred_hour: "Occurred Hour"
  x: "x"
  y: "y"
