column_mapping:
  id: "OBJECTID"
  vehicle_year: "Vehicle Year"
  vehicle_make: "Vehicle Make"
  vehicle_model: "Vehicle Model"
  vehicle_style: "Vehicle Style"
  vehicle_colour: "Vehicle Colour"
  vehicle_value: "Vehicle Value"
  weekday: "Weekday"
  recovered: "Recovered"
  neighbourhood: "Neighbourhood"
  ward: "Ward"
  sector: "Sector"
  reported_date: "Reported Date"
  occurred_date: "Occurred Date"
  year: "Year"
  intersection: "Intersection"
  division: "Division"
  census_tract: "Census Tract"
  time_of_day: "Time of Day"
  councillor: "Councillor"
  reported_hour: "Reported Hour"
  occurred_hour: "Occurred Hour"
  x: "x"
  y: "y"
