export const colors = {
  light: {
    background: '#FFFFFF',
    surface: '#F5F5F5',
    surfaceSecondary: '#EBEBEB',
    text: '#1A1A1A',
    textSecondary: '#666666',
    textTertiary: '#999999',
    border: '#E0E0E0',
    primary: '#007AFF',
    primaryLight: '#E8F2FF',
    userBubble: '#007AFF',
    userBubbleText: '#FFFFFF',
    assistantBubble: '#F0F0F0',
    assistantBubbleText: '#1A1A1A',
    error: '#FF3B30',
    success: '#34C759',
    destructive: '#FF3B30',
    inputBackground: '#F5F5F5',
    headerBackground: '#FFFFFF',
    tabBar: '#FFFFFF',
    card: '#FFFFFF',
  },
  dark: {
    background: '#000000',
    surface: '#1C1C1E',
    surfaceSecondary: '#2C2C2E',
    text: '#FFFFFF',
    textSecondary: '#ABABAB',
    textTertiary: '#636366',
    border: '#38383A',
    primary: '#0A84FF',
    primaryLight: '#1A2A3A',
    userBubble: '#0A84FF',
    userBubbleText: '#FFFFFF',
    assistantBubble: '#1C1C1E',
    assistantBubbleText: '#FFFFFF',
    error: '#FF453A',
    success: '#30D158',
    destructive: '#FF453A',
    inputBackground: '#1C1C1E',
    headerBackground: '#000000',
    tabBar: '#1C1C1E',
    card: '#1C1C1E',
  },
} as const;

export type ThemeColors = {
  [K in keyof typeof colors.light]: string;
};
