"""
Tests for FastAPI docs exposure in InferenceServer.
"""

import sys
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import Mock, patch

from fastapi import FastAPI

# Add server directory to Python path
SCRIPT_DIR = Path(__file__).parent.absolute()
SERVER_DIR = SCRIPT_DIR.parent.parent
sys.path.insert(0, str(SERVER_DIR))

from inference_server import InferenceServer


class _DummyStaticFiles:
    """Minimal ASGI app used to avoid filesystem coupling in tests."""

    def __init__(self, *args, **kwargs):
        pass

    async def __call__(self, scope, receive, send):
        return None


class _DummyFastMCP:
    """Minimal MCP adapter used to avoid external initialization in tests."""

    @staticmethod
    def from_fastapi(app, name):
        return SimpleNamespace(http_app=lambda: FastAPI())


class TestInferenceServerDocsExposure:
    """Verify that autogenerated docs are gated by ENVIRONMENT."""

    def _build_server(self):
        mock_logger = Mock()
        mock_thread_pool_manager = Mock()
        mock_thread_pool_manager.get_pool.return_value = Mock()

        with patch("inference_server.load_config", return_value={}), \
             patch("inference_server.LoggingConfigurator.setup_initial_logging", return_value=mock_logger), \
             patch("inference_server.LoggingConfigurator.setup_full_logging", return_value=mock_logger), \
             patch("inference_server.ConfigResolver"), \
             patch("inference_server.ServiceFactory"), \
             patch("inference_server.RouteConfigurator") as mock_route_configurator, \
             patch("inference_server.ConfigurationSummaryLogger"), \
             patch("inference_server.DatasourceFactory"), \
             patch("inference_server.ThreadPoolManager", return_value=mock_thread_pool_manager), \
             patch("inference_server.MiddlewareConfigurator.configure_middleware"), \
             patch("inference_server.setup_aiohttp_session_tracking"), \
             patch("inference_server.StaticFiles", _DummyStaticFiles), \
             patch("inference_server.FastMCP", _DummyFastMCP):
            mock_route_configurator.return_value.configure_routes.return_value = None
            return InferenceServer(config_path="test-config.yaml")

    def test_docs_disabled_in_production(self, monkeypatch):
        """Production should disable autogenerated API docs and schema routes."""
        monkeypatch.setenv("ENVIRONMENT", "production")

        server = self._build_server()

        assert server.app.docs_url is None
        assert server.app.redoc_url is None
        assert server.app.openapi_url is None

    def test_docs_enabled_outside_production(self, monkeypatch):
        """Non-production environments should keep autogenerated docs enabled."""
        monkeypatch.setenv("ENVIRONMENT", "development")

        server = self._build_server()

        assert server.app.docs_url == "/docs"
        assert server.app.redoc_url == "/redoc"
        assert server.app.openapi_url == "/openapi.json"
