column_mapping:
  id: "OBJECTID"
  year: "Year"
  reported_date: "Reported Date"
  reported_hour: "Reported Hour"
  occurred_date: "Occurred Date"
  occurred_hour: "Occurred Hour"
  weekday: "Weekday"
  offence_summary: "Offence Summary"
  offence_category: "Offence Category"
  neighbourhood: "Neighbourhood Name"
  sector: "Sector"
  division: "Division"
  census_tract: "Census Tract"
  time_of_day: "Time of Day"
  ward: "Ward"
  councillor: "Councillor"
  intersection: "Intersection"
  x: "x"
  y: "y"
