domain_name: E-Commerce
description: Customer order management system

# NEW: Domain metadata for strategy selection
domain_type: ecommerce
semantic_types:
  order_identifier:
    description: "Unique identifier for an order"
    patterns: ["order", "id", "number"]
  monetary_amount:
    description: "Currency amounts"
    patterns: ["amount", "total", "price", "cost"]
  time_period:
    description: "Time duration"
    patterns: ["days", "weeks", "months"]
  person_name:
    description: "Customer or person name"
    patterns: ["name", "customer", "client"]
  contact_email:
    description: "Email address"
    patterns: ["email", "mail", "contact"]
  order_status:
    description: "Order status or state"
    patterns: ["status", "state", "condition"]
  date_value:
    description: "Date values in various formats"
    patterns: ["date", "day", "time", "when", "on"]
    regex_patterns:
      - '\b\d{4}-\d{2}-\d{2}\b'  # YYYY-MM-DD
      - '\b\d{2}/\d{2}/\d{4}\b'  # MM/DD/YYYY
  city_name:
    description: "City or location names"
    patterns: ["city", "location", "from the", "in", "located in"]
  payment_method:
    description: "Payment method types"
    patterns: ["payment", "pay", "paid", "method"]

# Vocabulary for natural language understanding
vocabulary:
  entity_synonyms:
    customer: ["client", "buyer", "purchaser", "user", "account holder"]
    order: ["purchase", "transaction", "sale", "invoice", "receipt"]
  action_verbs:
    find: ["show", "list", "get", "find", "display", "retrieve", "lookup", "search"]
    calculate: ["sum", "total", "calculate", "compute", "aggregate", "count"]
    filter: ["filter", "only", "just", "where", "with", "having"]
    sort: ["sort", "order", "arrange", "rank"]
  field_synonyms:
    name: ["customer name", "client name", "buyer name"]
    total: ["amount", "sum", "grand total", "price"]
    status: ["state", "condition", "stage"]

entities:
  customer:
    name: customer
    entity_type: primary
    table_name: customers
    description: Customer information
    primary_key: id
    display_name_field: name
    searchable_fields:
    - name
    - email
    - phone
    common_filters:
    - city
    - country
    - created_at
    default_sort_field: created_at
    default_sort_order: DESC
  order:
    name: order
    entity_type: transaction
    table_name: orders
    description: Customer orders
    primary_key: id
    display_name_field: id
    searchable_fields:
    - id
    - status
    common_filters:
    - status
    - payment_method
    - order_date
    - total
    default_sort_field: order_date
    default_sort_order: DESC
fields:
  customer:
    id:
      name: id
      data_type: integer
      db_column: id
      description: Customer ID
      required: true
      searchable: true
      filterable: true
      sortable: true
      display_format: null
      validation_rules: []
      aliases: []
      enum_values: null
    name:
      name: name
      data_type: string
      db_column: name
      description: Customer name
      required: true
      searchable: true
      filterable: true
      sortable: true
      display_format: null
      validation_rules: []
      aliases:
      - customer name
      - client name
      - buyer name
      enum_values: null
      # NEW: Semantic metadata
      semantic_type: person_name
      summary_priority: 9
      extraction_hints:
        look_for_quotes: true
        capitalization_required: true
    email:
      name: email
      data_type: string
      db_column: email
      description: Customer email
      required: true
      searchable: true
      filterable: true
      sortable: true
      display_format: email
      validation_rules: []
      aliases: []
      enum_values: null
      # NEW: Semantic metadata
      semantic_type: contact_email
      summary_priority: 8
      extraction_pattern: '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
    phone:
      name: phone
      data_type: string
      db_column: phone
      description: Phone number
      required: false
      searchable: true
      filterable: true
      sortable: true
      display_format: phone
      validation_rules: []
      aliases: []
      enum_values: null
    city:
      name: city
      data_type: string
      db_column: city
      description: City
      required: false
      searchable: false
      filterable: true
      sortable: true
      display_format: null
      validation_rules: []
      aliases: []
      enum_values: null
    country:
      name: country
      data_type: string
      db_column: country
      description: Country
      required: false
      searchable: false
      filterable: true
      sortable: true
      display_format: null
      validation_rules: []
      aliases: []
      enum_values: null
    created_at:
      name: created_at
      data_type: datetime
      db_column: created_at
      description: Customer creation date
      required: true
      searchable: false
      filterable: true
      sortable: true
      display_format: date
      validation_rules: []
      aliases: []
      enum_values: null
      # NEW: Semantic metadata
      semantic_type: date_value
      summary_priority: 7
      extraction_hints:
        formats: ["YYYY-MM-DD", "DD-MM-YYYY", "MM/DD/YYYY", "Month DD, YYYY"]
        relative_terms: ["today", "yesterday", "this week", "last month"]
  order:
    id:
      name: id
      data_type: integer
      db_column: id
      description: Order ID
      required: true
      searchable: true
      filterable: true
      sortable: true
      display_format: null
      validation_rules: []
      aliases: []
      enum_values: null
      # NEW: Semantic metadata
      semantic_type: order_identifier
      summary_priority: 10
      extraction_hints:
        patterns: ["order #", "order number", "#"]
        numeric_required: true
    customer_id:
      name: customer_id
      data_type: integer
      db_column: customer_id
      description: Customer ID
      required: true
      searchable: false
      filterable: true
      sortable: true
      display_format: null
      validation_rules: []
      aliases: []
      enum_values: null
    order_date:
      name: order_date
      data_type: datetime
      db_column: order_date
      description: Order date
      required: true
      searchable: false
      filterable: true
      sortable: true
      display_format: date
      validation_rules: []
      aliases: []
      enum_values: null
      # NEW: Semantic metadata
      semantic_type: date_value
      summary_priority: 9
      extraction_hints:
        formats: ["YYYY-MM-DD", "DD-MM-YYYY", "MM/DD/YYYY", "Month DD, YYYY"]
        relative_terms: ["today", "yesterday", "this week", "last month"]
        patterns: ["on", "from", "since", "after", "before"]
    total:
      name: total
      data_type: decimal
      db_column: total
      description: Order total amount
      required: true
      searchable: false
      filterable: true
      sortable: true
      display_format: currency
      validation_rules: []
      aliases: []
      enum_values: null
      # NEW: Semantic metadata
      semantic_type: monetary_amount
      summary_priority: 8
      extraction_hints:
        currency_symbols: ["$", "USD", "dollars"]
        decimal_places: 2
    status:
      name: status
      data_type: enum
      db_column: status
      description: Order status
      required: true
      searchable: true
      filterable: true
      sortable: true
      display_format: null
      validation_rules: []
      aliases: []
      enum_values:
      - pending
      - processing
      - shipped
      - delivered
      - cancelled
      # NEW: Semantic metadata
      semantic_type: order_status
      summary_priority: 8
    payment_method:
      name: payment_method
      data_type: enum
      db_column: payment_method
      description: Payment method
      required: false
      searchable: false
      filterable: true
      sortable: true
      display_format: null
      validation_rules: []
      aliases: []
      enum_values:
      - credit_card
      - debit_card
      - paypal
      - bank_transfer
      - cash
    shipping_address:
      name: shipping_address
      data_type: string
      db_column: shipping_address
      description: Shipping address
      required: false
      searchable: false
      filterable: true
      sortable: true
      display_format: null
      validation_rules: []
      aliases: []
      enum_values: null
    shipping_city:
      name: shipping_city
      data_type: string
      db_column: shipping_city
      description: Shipping city
      required: false
      searchable: false
      filterable: true
      sortable: true
      display_format: null
      validation_rules: []
      aliases: []
      enum_values: null
    shipping_country:
      name: shipping_country
      data_type: string
      db_column: shipping_country
      description: Shipping country
      required: false
      searchable: false
      filterable: true
      sortable: true
      display_format: null
      validation_rules: []
      aliases: []
      enum_values: null
relationships:
- name: customer_orders
  from_entity: customer
  to_entity: order
  relation_type: one_to_many
  from_field: id
  to_field: customer_id
  join_type: INNER
  description: Customer has many orders
query_patterns: []
vocabulary:
  entity_synonyms:
    customer:
    - client
    - buyer
    - user
    - purchaser
    - shopper
    order:
    - purchase
    - transaction
    - sale
    - invoice
  action_verbs:
    find:
    - show
    - list
    - get
    - find
    - display
    - retrieve
    calculate:
    - sum
    - total
    - calculate
    - compute
    - aggregate
    filter:
    - filter
    - only
    - just
    - where
    - with
  time_expressions:
    today: '0'
    yesterday: '1'
    this week: '7'
    last week: '14'
    this month: '30'
    last month: '60'
    this year: '365'
  date_formats:
    iso_date: 'YYYY-MM-DD'
    european_date: 'DD-MM-YYYY'
    us_date: 'MM/DD/YYYY'
    us_date_dash: 'MM-DD-YYYY'
    natural_date: 'Month DD, YYYY'
    short_date: 'Mon DD, YYYY'
  value_expressions: {}
  common_phrases:
    date_phrases:
      - "on [date]"
      - "from [date]"
      - "since [date]"
      - "after [date]"
      - "before [date]"
      - "between [date] and [date]"
      - "from [date] to [date]"
    date_examples:
      - "on July 20th 2025"
      - "from 20-09-2025"
      - "since 2025-07-20"
      - "after 09/20/2025"
      - "before 20-07-2025"
metadata: {}
